server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spring?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver