
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/crawler?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # jpa配置
  jpa:
    database: MySQL
    show-sql: false


# es 服务地址
elasticsearch:
  host: 127.0.0.1
  # es 服务端口
  port: 9200


# 配置日志级别,开启 debug 日志
#  logging.level.top.iaminlearn.es=debug
#logging:
server:
  port: 8000
#  level: debug